#
import os
from datetime import datetime
import logger

def iterPythonFiles(root):
    for dirpath, dirnames, filenames in os.walk(root):
        filtered = []
        for dirname in dirnames:
            if dirname.startswith('_'):
                continue
            if dirname in ('dev', '.git', '.vscode'):
                continue
            filtered.append(dirname)
        dirnames[:] = filtered
        for filename in filenames:
            if not filename.endswith('.py'):
                continue
            if filename.startswith('_'):
                continue
            yield f'{dirpath}/{filename}'

here = __file__
print(f'UPDATING version in "{here}"')
package_root = os.path.dirname(os.path.dirname(here))
mtimes = []
for path in iterPythonFiles(package_root):
    mtimes.append(os.path.getmtime(path))
mtime = max(mtimes)

dt = datetime.fromtimestamp(mtime)
part_year = dt.strftime('%y')

month_str = dt.strftime('%m')
if month_str.startswith('0'):
    middle = str(dt.timetuple().tm_yday)
else:
    middle = dt.strftime('%m%d')

hour_str = dt.strftime('%H')
if hour_str.startswith('0'):
    millis = int(dt.microsecond/1000)
    seconds_since_midnight = 1000*(dt.hour*3600 + dt.minute*60 + dt.second) + millis
    tail = str(seconds_since_midnight)
else:
    tail = dt.strftime('%H%M')

timestomp = f'{part_year}.{middle}.{tail}'

print(f'\nBUILD ({os.path.abspath(".")})\n')

tmp_path = 'dev/_blender_manifest.toml'
dst_path = 'src/fotographie/blender_manifest.toml'

out = open(tmp_path, 'w', newline='\n')
autogen_warning = '''# ============================================== #
# === AUTOGENERATED FILE - EDIT AT OWN RISK! === #
# ============================================== #

'''
out.write(autogen_warning)

logger_warning = '''
'WARNING: in src/fotographie/logger.py, `g_log_level` set to LEVEL_DEBUG'=''
'''.lstrip()
if logger.g_log_level >= logger.LEVEL_INFO:
    logger_warning = ''

with open('dev/blender_manifest.toml', 'r') as f:
    lines = f.readlines()
    for line in lines:
        if line.startswith('version ='):
            line = f"version = '{timestomp}'\n"
        if logger_warning and line.startswith('[permissions]'):
            line += logger_warning
        out.write(line)

out.close()

# write the temp file first
# tmp_path.write_text(new_contents, encoding='utf-8')

# atomically overwrite the old manifest
os.replace(tmp_path, dst_path)
