#
import os
from datetime import datetime
from pathlib import Path
# os.chdir(os.path.dirname(os.path.abspath(__file__)) + '/..')

# now = datetime.datetime.now()
# version = (now.year % 100, now.month*100 + now.day, now.hour*100 + now.minute)
from ..auto_load import iter_submodule_names as getSubmodules
mtimes = []

for name in list(getSubmodules(Path('.').parent)):
    if name != 'auto_load':
        module_path = Path(name).with_suffix('.py')
        mtime = os.path.getmtime(module_path)
        mtimes.append(mtime)
mtime = max(mtimes)

timestomp = datetime.fromtimestamp(mtime).strftime('%y.%m%d.%H%M')
# version = tuple(x for x in timestomp.split(','))

print(f'\nBUILD ({os.path.abspath(".")})\n')

tmp_path = Path('dev/_blender_manifest.toml')
dst_path = Path('blender_manifest.toml')

out = open(tmp_path, 'w')
autogen_warning = '''# ============================================== #
# === AUTOGENERATED FILE - EDIT AT OWN RISK! === #
# ============================================== #

'''
out.write(autogen_warning)

with open('dev/blender_manifest.toml', 'r') as f:
    lines = f.readlines()
    for line in lines:
        if line.startswith('version ='):
            print('old', line)
            line = f"version = '{timestomp}'\n"
        out.write(line)

out.close()

# write the temp file first
# tmp_path.write_text(new_contents, encoding='utf-8')

# atomically overwrite the old manifest
os.replace(tmp_path, dst_path)
