#
import os
from datetime import datetime

def iterPythonFiles(root):
    for dirpath, dirnames, filenames in os.walk(root):
        filtered = []
        for dirname in dirnames:
            if dirname.startswith('_'):
                continue
            if dirname in ('dev', '__pycache__', '.git', '.vscode'):
                continue
            filtered.append(dirname)
        dirnames[:] = filtered
        for filename in filenames:
            if not filename.endswith('.py'):
                continue
            if filename.startswith('_'):
                continue
            yield f'{dirpath}/{filename}'

here = __file__
print(f'UPDATING version in "{here}"')
package_root = os.path.dirname(os.path.dirname(here))
mtimes = []
for path in iterPythonFiles(package_root):
    mtimes.append(os.path.getmtime(path))
mtime = max(mtimes)

dt = datetime.fromtimestamp(mtime)
part_year = dt.strftime('%y')

month_str = dt.strftime('%m')
if month_str.startswith('0'):
    middle = str(dt.timetuple().tm_yday)
else:
    middle = dt.strftime('%m%d')

hour_str = dt.strftime('%H')
if hour_str.startswith('0'):
    millis = int(dt.microsecond/1000)
    seconds_since_midnight = 1000*(dt.hour*3600 + dt.minute*60 + dt.second) + millis
    tail = str(seconds_since_midnight)
else:
    tail = dt.strftime('%H%M')

timestomp = f'{part_year}.{middle}.{tail}'

print(f'\nBUILD ({os.path.abspath(".")})\n')

tmp_path = 'dev/_blender_manifest.toml'
dst_path = 'src/fotographie/blender_manifest.toml'

out = open(tmp_path, 'w', newline='\n')
autogen_warning = '''# ============================================== #
# === AUTOGENERATED FILE - EDIT AT OWN RISK! === #
# ============================================== #

'''
out.write(autogen_warning)

with open('dev/blender_manifest.toml', 'r') as f:
    lines = f.readlines()
    for line in lines:
        if line.startswith('version ='):
            line = f"version = '{timestomp}'\n"
        out.write(line)

out.close()

# write the temp file first
# tmp_path.write_text(new_contents, encoding='utf-8')

# atomically overwrite the old manifest
os.replace(tmp_path, dst_path)

## ------ ##
# import shutil

# OUT_ROOT = 'build'
# PACKAGE = 'fotographie'
# OUT_DIR = f'{OUT_ROOT}/{PACKAGE}'

# def ensure_dir(path):
#     if path and not os.path.isdir(path):
#         os.makedirs(path, exist_ok=True)

# def copy_file(src, dst):
#     folder = os.path.dirname(dst)
#     ensure_dir(folder)
#     shutil.copy2(src, dst)

# def copy_tree(src, dst):
#     if os.path.isdir(dst):
#         shutil.rmtree(dst)
#     shutil.copytree(src, dst, dirs_exist_ok=True)

# if os.path.isdir(OUT_DIR):
#     shutil.rmtree(OUT_DIR)
# ensure_dir(OUT_DIR)

# INCLUDE = [
#     '__init__.py',
#     'auto_load.py',
#     'light_meter.py',
#     'main.py',
#     'meter_font.py',
#     'blender_manifest.toml',
# ]

# for entry in INCLUDE:
#     src = entry
#     dst = f'{OUT_DIR}/{entry}'
#     if os.path.isdir(src):
#         copy_tree(src, dst)
#     elif os.path.isfile(src):
#         copy_file(src, dst)
